# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- script: chmod +x ./gradlew

- task: Gradle@2
  displayName: 'Building Project'
  continueOnError: false
  inputs:
    gradleWrapperFile: './gradlew'
    tasks: 'assembleDebug'
    publishJUnitResults: true
    testResultsFiles: 'app/build/test-results/azure-pipelines'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false   
  
- bash: |
    ./gradlew test
  displayName: 'Running Tests'

#- bash: |
#    ./gradlew assemble
#  displayName: 'Running Tests'
#  continueOnError: false
